### ISSUE TITLE
Sbt-buildo downloads scala 2.10.5 dependencies

### ISSUE THREAD

**Issue by calippo** [buildo/sbt-buildo#5]
## description
Sbt-buildo downloads scala 2.10.5 dependencies.
This involves weird bugs such as https://github.com/spray/spray/issues/1036

<img width="849" alt="screen shot 2016-11-24 at 18 19 20" src="https://cloud.githubusercontent.com/assets/2476080/20607019/6714bfdc-b275-11e6-902e-bb29939cfbcd.png">

## how to reproduce
- Build a project using sbt-buildo from scratch

**Comment by gabro** [comment]
I finally understood this bug.

The scala version has nothing to do with it. Scala 2.10.5 is used for building sbt itself, so it's ok.

The problem with the spray DSL is caused by the "-Yno-adapted-args" flag, which prevents auto-tupling from happening (see http://stackoverflow.com/questions/29252205/why-this-case-class-can-hold-more-parameters-than-it-declares). Since spray DSL heavily relies on auto-tupling, it fails to compile with that flag on.

Removing the flag fixes the issue. I'll publish an updated version soon.

**Comment by gabro** [comment]
Published in v0.1.6 🎉
